{% set name = "pydit-jceresearch" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydit-jceresearch-{{ version }}.tar.gz
  sha256: 064d8496d59ec4ef1eab504129ea51bb350275991626662762baed9c9f6ba762

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - matplotlib-base
    - myst-parser
    - numpy >=1.22,<2.0
    - openpyxl >=3.0.0,<4.0.0
    - pandas >=1.2.1,<2.0.0
    - python >=3.6,<4.0

test:
  imports:
    - pydit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pydit-jceresearch/
  summary: Data cleansing tools for Internal Auditors
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jceresearch
